# tasks file
---
- name: configure | apache htpasswd users
  community.general.htpasswd:
    path: /etc/nagios3/htpasswd.users
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    mode: '0644'
  with_items: "{{ nagios_server_htpasswd_users }}"
  tags:
    - nagios-server-configure-apache-htpasswd-users

- name: configure | copy cgi file
  ansible.builtin.template:
    src: etc/nagios3/cgi.cfg.j2
    dest: /etc/nagios3/cgi.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    # Needed for www-data to read this file
    mode: '0644'
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-cgi-file

- name: configure | copy commands file
  ansible.builtin.template:
    src: etc/nagios3/commands.cfg.j2
    dest: /etc/nagios3/commands.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-commands-file

- name: configure | copy resource file
  ansible.builtin.template:
    src: etc/nagios3/resource.cfg.j2
    dest: /etc/nagios3/resource.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-resource-file

- name: configure | copy contacts files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/contacts_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/contacts_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-contacts-files

- name: configure | copy hostextinfo files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/extinfo_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/extinfo_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-hostextinfo-files

- name: configure | copy hostgroups files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/hostgroups_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/hostgroups_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-hostgroups-files

- name: configure | copy generic service template file
  ansible.builtin.template:
    src: etc/nagios3/conf.d/generic-service_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/generic-service_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-generic-service-template-file

- name: configure | copy services files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/services_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/services_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-services-files

- name: configure | copy timeperiods files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/timeperiods_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/timeperiods_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-timeperiods-files

- name: configure | copy generic host template file
  ansible.builtin.template:
    src: etc/nagios3/conf.d/generic-host_nagios2.cfg.j2
    dest: /etc/nagios3/conf.d/generic-host_nagios2.cfg
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-generic-host-template-file

- name: configure | copy host files
  ansible.builtin.template:
    src: etc/nagios3/conf.d/hostname_nagios2.cfg.j2
    dest: "/etc/nagios3/conf.d/{{ item.name }}_nagios2.cfg"
    owner: "{{ nagios_server_default_owner }}"
    group: "{{ nagios_server_default_group }}"
    mode: "{{ nagios_server_default_file_mode }}"
  with_items: "{{ nagios_server_hosts }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-copy-host-files

- name: configure | check external commands
  when: nagios_server_check_external_commands | bool
  tags:
    - nagios-server-configure-check-external-commands
  block:
    - name: configure | set command dir permissions
      ansible.builtin.file:
        path: /var/lib/nagios3/rw
        state: directory
        mode: 'g+x'
        # Needed for www-data to access this directory
    - name: configure | add www-data user to nagios group
      ansible.builtin.user:
        name: www-data
        groups: "{{ nagios_server_default_group }}"
        append: true
    - name: configure | check external commands option
      ansible.builtin.lineinfile:
        path: "{{ nagios_server_etc_nagios3_nagios_file }}"
        regexp: '^check_external_commands='
        line: check_external_commands=1
      notify: reload nagios-server

- name: configure | regular expression matching option
  ansible.builtin.lineinfile:
    path: "{{ nagios_server_etc_nagios3_nagios_file }}"
    regexp: '^use_regexp_matching='
    line: use_regexp_matching=1
  when: nagios_server_use_regexp_matching | bool
  notify: reload nagios-server
  tags:
    - nagios-server-configure-use-regexp-matching

- name: configure | remove paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nagios_server_absent_paths }}"
  notify: reload nagios-server
  tags:
    - nagios-server-configure-remove
