# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ nagios_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  register: _apt_result
  until: _apt_result is succeeded
