# tasks file
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-include-variables

- include: install.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-install

- include: private-keys.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-private-keys

#- include: configure.yml
#  tags:
#    - configuration
#    - nagios-server
#    - nagios-server-configure

- name: start and enable service
  service:
    name: "nagios{{ nagios_server_major_version }}"
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - nagios-server
    - nagios-server-start-enable-service
