# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-include-variables

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-install

- ansible.builtin.import_tasks: private-keys.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-private-keys

- name: configure
  block:
    - name: >
      ansible.builtin.include_tasks: configure-3.yml
      when: nagios_server_major_version is version('3', '=')

    - name: >
      ansible.builtin.include_tasks: configure-4.yml
      when: nagios_server_major_version is version('4', '=')
  tags:
    - configuration
    - nagios-server
    - nagios-server-configure

- name: start and enable service
  ansible.builtin.service:
    name: "nagios{{ nagios_server_major_version }}"
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - nagios-server
    - nagios-server-start-enable-service
