# tasks file
---
- include: install.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-install

- include: private-keys.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-private-keys

- include: configure.yml
  tags:
    - configuration
    - nagios-server
    - nagios-server-configure

- name: start and enable service
  service:
    name: nagios3
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - nagios-server
    - nagios-server-start-enable-service
