# tasks file
---
- name: private keys | create ssh directory
  ansible.builtin.file:
    path: "~{{ item.owner | default('nagios') }}/.ssh"
    state: directory
    owner: "{{ item.owner | default('nagios') }}"
    group: "{{ item.group | default(item.owner) | default('nagios') }}"
    mode: 0700
  with_items: "{{ nagios_server_private_keys }}"
  when: item.state is undefined or item.state == 'present'
  tags:
    - nagios-server-private-keys-create-ssh-directory

- name: private keys | add
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "~{{ item.owner | default('nagios') }}/.ssh/{{ item.dest | default(item.src | basename) }}"
    owner: "{{ item.owner | default('nagios') }}"
    group: "{{ item.group | default(item.owner) | default('nagios') }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: "{{ nagios_server_private_keys }}"
  when: item.state is undefined or item.state == 'present'
  tags:
    - nagios-server-private-keys-add

- name: private keys | remove
  ansible.builtin.file:
    path: "~{{ item.owner }}/.ssh/{{ item.dest | default(item.src | basename) }}"
    state: absent
  with_items: "{{ nagios_server_private_keys }}"
  when:
    - item.state is defined
    - item.state == 'absent'
  tags:
    - nagios-server-private-keys-remove
