# handlers file
---
- name: reload nagios-server
  ansible.builtin.service:
    name: "nagios{{ nagios_server_major_version }}"
    state: reloaded
  when: service_default_state | default('started') == 'started'
